version: 0.0.1
name: 'Jet Met Efficiencies'

input:
  files:
      # Single Muons
       -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/bundocka/cmsl1t/sm_noLowEtSF_101.root
  sample:
    name: Data
    title: 2017 Data
  trigger:
    name: smNoLowEtSF
    title: Single Muon
  pileup_file: ""
  run_number: ""
  lumi_json: "https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions17/13TeV/PromptReco/Cert_294927-306462_13TeV_PromptReco_Collisions17_JSON.txt"  

analysis:
  do_emu: True
  do_reco: True
  do_vertex: False
  do_gen: False
  do_fit: True
  pu_type: 0PU24,25PU49,50PU
  pu_bins: [0,25,50,999]
  thresholds:
    HT: [120, 200, 320]
    HT_Emu: [120, 200, 320]
    METBE: [80, 100, 120]
    METBE_Emu: [80, 100, 120]
    METHF: [80, 100, 120]
    METHF_Emu: [80, 100, 120]
    JetET: [35, 90, 120]
    JetET_Emu: [35, 90, 120]

  analyzers:
     - cmsl1t.analyzers.jetMet_analyzer
  producers: []
  progress_bar:
    report_every: 1000

output:
  template:
     - output/constant_rate_turnons
     - "{date}_{run_number}_{sample_name}_{trigger_name}"
