version: 1
name: 'Jet Met Efficiencies'

input:
  files:
      # Single Muons
       -  root://eoscms.cern.ch//eos/cms//store/group/dpg_trigger/comm_trigger/L1Trigger/bundocka/SingleMuon/smMETa/181211_183526/0000/L1Ntuple_*.root
       -  root://eoscms.cern.ch//eos/cms//store/group/dpg_trigger/comm_trigger/L1Trigger/bundocka/SingleMuon/smMETb/181211_183601/0000/L1Ntuple_*.root
       -  root://eoscms.cern.ch//eos/cms//store/group/dpg_trigger/comm_trigger/L1Trigger/bundocka/SingleMuon/smMETc/181211_183639/0000/L1Ntuple_*.root
       -  root://eoscms.cern.ch//eos/cms//store/group/dpg_trigger/comm_trigger/L1Trigger/bundocka/SingleMuon/smMETd/181211_183713/0000/L1Ntuple_*.root
       -  root://eoscms.cern.ch//eos/cms//store/group/dpg_trigger/comm_trigger/L1Trigger/bundocka/SingleMuon/smMETe/181211_183750/0000/L1Ntuple_*.root
  sample:
    name: Data
    title: 2018 Data
  trigger:
    name: smMET
    title: Single Muon
  pileup_file: ""
  run_number: ""
  lumi_json: "https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions18/13TeV/PromptReco/Cert_314472-325175_13TeV_PromptReco_Collisions18_JSON.txt" 
  ntuple_map_file: config/ntuple_content_AODRAWEMU.yaml

analysis:
  load_trees:
    - event
    - upgrade
    - emuCaloTowers
    - emuUpgrade
    - jetReco
    - metFilterReco
    - recoTree
  do_fit: True
  pu_type: 0PU24,25PU49,50PU
  pu_bins: [0,25,50,999]
  thresholds:
    HT:           [120, 200, 320]
    HT_Emu:       [120, 200, 320]
    METBE:        [80, 100, 120]
    METBE_Emu:    [80, 100, 120]
    METHF:        [80, 100, 120]
    METHF_Emu:    [80, 100, 120]
    JetET_BE:     [35, 90, 120]
    JetET_BE_Emu: [35, 90, 120]
    JetET_HF:     [35, 90, 120]
    JetET_HF_Emu: [35, 90, 120]

  analyzers:
     jetMet_analyzer:
       module: cmsl1t.analyzers.jetMet_analyzer
  producers:
    l1Sums:
      module: cmsl1t.producers.l1sums
      inputs:
        - L1Upgrade_sumBx
        - L1Upgrade_sumType
        - L1Upgrade_sumEt
        - L1Upgrade_sumPhi
      outputs:
        - l1Sums
    l1EmuSums:
      module: cmsl1t.producers.l1sums
      inputs:
        - emu_L1Upgrade_sumBx
        - emu_L1Upgrade_sumType
        - emu_L1Upgrade_sumEt
        - emu_L1Upgrade_sumPhi
      outputs:
        - l1EmuSums
    goodPFJets:
      module: cmsl1t.producers.jets
      inputs:
        - Jet_et
        - Jet_eta
        - Jet_phi
        - Jet_etCorr
        - Jet_cemef
        - Jet_chef
        - Jet_cMult
        - Jet_mef
        - Jet_muMult
        - Jet_nemef
        - Jet_nhef
        - Jet_nMult
      jetType: PF
      filter: cmsl1t.filters.jets.pfJetFilter
      outputs:
        - goodPFJets
    caloJets:
      module: cmsl1t.producers.jets
      inputs:
        - Jet_caloEt
        - Jet_caloEta
        - Jet_caloPhi
        - Jet_caloEtCorr
      jetType: Calo
      filter: null
      outputs:
        - caloJets
    l1Jets:
      module: cmsl1t.producers.jets
      inputs:
        - L1Upgrade_jetEt
        - L1Upgrade_jetEta
        - L1Upgrade_jetPhi
        - L1Upgrade_jetBx
      jetType: L1
      filter: null
      outputs:
        - l1Jets
    l1EmuJets:
      module: cmsl1t.producers.jets
      inputs:
        - emu_L1Upgrade_jetEt
        - emu_L1Upgrade_jetEta
        - emu_L1Upgrade_jetPhi
        - emu_L1Upgrade_jetBx
      jetType: L1
      filter: null
      outputs:
        - l1EmuJets

output:
  template:
     - output/constant_rate_turnons
     - "{date}_{sample_name}_{trigger_name}"
